using System.Diagnostics;
using EatForm.Entities;

namespace EatForm;

public class DbSeeder
{
    private readonly EatFormDbContext _dbContext;

    public DbSeeder(EatFormDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public void Seed()
    {
        // 1. Users
        if (!_dbContext.Users.Any())
        {
            var users = GetUsers().ToList();
            _dbContext.Users.AddRange(users);
            _dbContext.SaveChanges();
        }

        var user1 = _dbContext.Users.First(u => u.Email == "rafal@example.com");
        var user2 = _dbContext.Users.First(u => u.Email == "anna@example.com");

        // 2. Workouts
        if (!_dbContext.Workouts.Any())
        {
            var workouts = new List<Workout>
            {
                new Workout { Name = "FBW A", UserId = user1.Id, Description = "Pełne ciało — wariant A", Type = "FBW", Difficulty = "Średni", IsPublic = true, CreatedAt = DateTime.UtcNow },
                new Workout { Name = "FBW B", UserId = user1.Id, Description = "Pełne ciało — wariant B", Type = "FBW", Difficulty = "Średni", IsPublic = true, CreatedAt = DateTime.UtcNow }
            };
            _dbContext.Workouts.AddRange(workouts);
            _dbContext.SaveChanges();
        }

        var workout1 = _dbContext.Workouts.First(w => w.Name == "FBW A");
        var workout2 = _dbContext.Workouts.First(w => w.Name == "FBW B");

        // 3. Exercises
        if (!_dbContext.Exercises.Any())
        {
            var exercises = new List<Exercise>
            {
                new Exercise { Name = "Przysiad ze sztangą", Sets = 4, Reps = 10, Weight = 60, RestTime = 120, WorkoutId = workout1.Id },
                new Exercise { Name = "Wyciskanie leżąc", Sets = 4, Reps = 8, Weight = 50, RestTime = 90, WorkoutId = workout1.Id },
                new Exercise { Name = "Martwy ciąg", Sets = 3, Reps = 6, Weight = 80, RestTime = 150, WorkoutId = workout2.Id },
                new Exercise { Name = "OHP", Sets = 3, Reps = 10, Weight = 30, RestTime = 90, WorkoutId = workout2.Id }
            };
            _dbContext.Exercises.AddRange(exercises);
            _dbContext.SaveChanges();
        }

        // 4. Workout Ratings
        if (!_dbContext.WorkoutRatings.Any())
        {
            var ratings = new List<WorkoutRating>
            {
                new WorkoutRating { WorkoutId = workout1.Id, UserId = user1.Id, Rating = 5, Comment = "Super trening", CreatedAt = DateTime.UtcNow },
                new WorkoutRating { WorkoutId = workout2.Id, UserId = user1.Id, Rating = 4, Comment = "Dobra intensywność", CreatedAt = DateTime.UtcNow }
            };
            _dbContext.WorkoutRatings.AddRange(ratings);
            _dbContext.SaveChanges();
        }

        // 5. Products
        if (!_dbContext.Products.Any())
        {
            var products = GetProducts().ToList();
            _dbContext.Products.AddRange(products);
            _dbContext.SaveChanges();
        }

        var product1 = _dbContext.Products.First(p => p.Name == "Kurczak (pierś)");
        var product2 = _dbContext.Products.First(p => p.Name == "Ryż biały");
        var product3 = _dbContext.Products.First(p => p.Name == "Owsianka");
        var product4 = _dbContext.Products.First(p => p.Name == "Banany");
        var product5 = _dbContext.Products.First(p => p.Name == "Jajka");

        // 6. Meal Plans
        if (!_dbContext.MealPlans.Any())
        {
            var mealPlans = new List<MealPlan>
            {
                new MealPlan { Name = "Plan na masę", TotalCalories = 3000, UserId = user1.Id, IsAutoGenerated = false, CreatedAt = DateTime.UtcNow },
                new MealPlan { Name = "Plan redukcyjny", TotalCalories = 2200, UserId = user2.Id, IsAutoGenerated = false, CreatedAt = DateTime.UtcNow }
            };
            _dbContext.MealPlans.AddRange(mealPlans);
            _dbContext.SaveChanges();
        }

        var plan1 = _dbContext.MealPlans.First(mp => mp.Name == "Plan na masę");
        var plan2 = _dbContext.MealPlans.First(mp => mp.Name == "Plan redukcyjny");

        // 7. Meals
        if (!_dbContext.Meals.Any())
        {
            var meals = new List<Meal>
            {
                new Meal { Name = "Kurczak z ryżem", TotalCalories = 515, MealPlanId = plan1.Id, Time = new TimeSpan(8,0,0) },
                new Meal { Name = "Owsianka z bananem", TotalCalories = 459, MealPlanId = plan1.Id, Time = new TimeSpan(10,30,0) },
                new Meal { Name = "Jajecznica", TotalCalories = 310, MealPlanId = plan2.Id, Time = new TimeSpan(8,0,0) }
            };
            _dbContext.Meals.AddRange(meals);
            _dbContext.SaveChanges();
        }

        var meal1 = _dbContext.Meals.First(m => m.Name == "Kurczak z ryżem");
        var meal2 = _dbContext.Meals.First(m => m.Name == "Owsianka z bananem");
        var meal3 = _dbContext.Meals.First(m => m.Name == "Jajecznica");

        // 8. Meal Products
        if (!_dbContext.MealProducts.Any())
        {
            var mealProducts = new List<MealProduct>
            {
                new MealProduct { MealId = meal1.Id, ProductId = product1.Id, Quantity = 150 },
                new MealProduct { MealId = meal1.Id, ProductId = product2.Id, Quantity = 100 },
                new MealProduct { MealId = meal2.Id, ProductId = product3.Id, Quantity = 80 },
                new MealProduct { MealId = meal2.Id, ProductId = product4.Id, Quantity = 120 },
                new MealProduct { MealId = meal3.Id, ProductId = product5.Id, Quantity = 3 }
            };
            _dbContext.MealProducts.AddRange(mealProducts);
            _dbContext.SaveChanges();
        }
    }

    private IEnumerable<User> GetUsers()
    {
        return new List<User>
        {
            new User { Email = "rafal@example.com", PasswordHash = "hashedpass", FirstName = "Rafał", LastName = "Majtczak", Age = 25, Weight = 74, Height = 180, ActivityLevel = "Medium", Goal = "Masa", Role = "user" },
            new User { Email = "anna@example.com", PasswordHash = "hashedpass", FirstName = "Anna", LastName = "Nowak", Age = 23, Weight = 60, Height = 165, ActivityLevel = "Low", Goal = "Redukcja", Role = "user" }
        };
    }

    private IEnumerable<Product> GetProducts()
    {
        return new List<Product>
        {
            new Product { Name = "Kurczak (pierś)", Calories = 165, Protein = 31, Carbs = 0, Fat = 3, IsGlobal = true },
            new Product { Name = "Ryż biały", Calories = 360, Protein = 7, Carbs = 80, Fat = 1, IsGlobal = true },
            new Product { Name = "Owsianka", Calories = 370, Protein = 13, Carbs = 60, Fat = 7, IsGlobal = true },
            new Product { Name = "Banany", Calories = 89, Protein = 1, Carbs = 23, Fat = 0, IsGlobal = true },
            new Product { Name = "Jajka", Calories = 155, Protein = 13, Carbs = 1, Fat = 11, IsGlobal = true }
        };
    }
}
