namespace EatForm.Entities;

public class MealPlan
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public int TotalCalories { get; set; }
    public bool IsAutoGenerated { get; set; } = false;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    
    public int UserId { get; set; }
    public User User { get; set; } = null!;

    
    public ICollection<Meal>? Meals { get; set; }
}