using AutoMapper;
using EatForm.Entities;
using EatForm.Models;
using Microsoft.EntityFrameworkCore;

namespace EatForm;

public interface IMealPlanService
{
    IEnumerable<MealPlanDto> GetAll();
    MealPlanDto GetById(int id);
    int CreateMealPlan(CreateMealPlanDto dto);
    void UpdateMealPlan(UpdateMealPlanDto dto, int id);
    void DeleteMealPlan(int id);
}

public class MealPlanService : IMealPlanService
{
    private readonly IMapper _mapper;
    private readonly EatFormDbContext _dbContext;

    public MealPlanService(IMapper mapper, EatFormDbContext dbContext)
    {
        _mapper = mapper;
        _dbContext = dbContext;
    }

    public IEnumerable<MealPlanDto> GetAll()
    {
        var mealPlans = _dbContext.MealPlans
            .Include(mp => mp.Meals)
            .ToList();

        return _mapper.Map<IEnumerable<MealPlanDto>>(mealPlans);
    }

    public MealPlanDto GetById(int id)
    {
        var mealPlan = _dbContext.MealPlans
            .Include(mp => mp.Meals)
            .FirstOrDefault(mp => mp.Id == id);

        if (mealPlan == null)
            throw new Exception("MealPlan not found");

        return _mapper.Map<MealPlanDto>(mealPlan);
    }

    public int CreateMealPlan(CreateMealPlanDto dto)
    {
        var mealPlan = _mapper.Map<MealPlan>(dto);
        mealPlan.CreatedAt = DateTime.Now;
        mealPlan.UserId = 1; 
        _dbContext.MealPlans.Add(mealPlan);
        _dbContext.SaveChanges();

        if (dto.Meals != null && dto.Meals.Count > 0)
        {
            foreach (var mealDto in dto.Meals)
            {
                var meal = _mapper.Map<Meal>(mealDto);
                meal.MealPlanId = mealPlan.Id;

                _dbContext.Meals.Add(meal);
            }

            _dbContext.SaveChanges();
        }

        // Suma kalorii posiłków
        mealPlan.TotalCalories = _dbContext.Meals
            .Where(m => m.MealPlanId == mealPlan.Id)
            .Sum(m => m.TotalCalories);

        _dbContext.SaveChanges();

        return mealPlan.Id;
    }

    public void UpdateMealPlan(UpdateMealPlanDto dto, int id)
    {
        var mealPlan = _dbContext.MealPlans
            .Include(mp => mp.Meals)
            .FirstOrDefault(mp => mp.Id == id);

        if (mealPlan == null)
            throw new Exception("MealPlan not found");

        mealPlan.Name = dto.Name;
        mealPlan.IsAutoGenerated = dto.IsAutoGenerated;

        // Usuń stare posiłki
        _dbContext.Meals.RemoveRange(mealPlan.Meals);
        _dbContext.SaveChanges();

        // Dodaj nowe posiłki
        if (dto.Meals != null && dto.Meals.Count > 0)
        {
            foreach (var mealDto in dto.Meals)
            {
                var meal = _mapper.Map<Meal>(mealDto);
                meal.MealPlanId = mealPlan.Id;

                _dbContext.Meals.Add(meal);
            }

            _dbContext.SaveChanges();
        }

        // Przeliczenie kalorii planu
        mealPlan.TotalCalories = _dbContext.Meals
            .Where(m => m.MealPlanId == mealPlan.Id)
            .Sum(m => m.TotalCalories);

        _dbContext.SaveChanges();
    }

    public void DeleteMealPlan(int id)
    {
        var mealPlan = _dbContext.MealPlans
            .Include(mp => mp.Meals)
            .FirstOrDefault(mp => mp.Id == id);

        if (mealPlan == null)
            throw new Exception("MealPlan not found");

        _dbContext.Meals.RemoveRange(mealPlan.Meals);
        _dbContext.MealPlans.Remove(mealPlan);
        _dbContext.SaveChanges();
    }
}
