namespace EatForm.Models;

public class MealPlanDto
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public int TotalCalories { get; set; }
    public bool IsAutoGenerated { get; set; } = false;
    public DateTime CreatedAt { get; set; }
    public List<MealDto> Meals { get; set; } = new();
}