namespace EatForm.Models;

public class UpdateMealPlanDto
{
    public string Name { get; set; } = null!;
    public int TotalCalories { get; set; } 
    public bool IsAutoGenerated { get; set; } = false;
    public List<CreateMealDto> Meals { get; set; } = new();
}
